version: '3.8'

services:
  db-ventas:
    image: mysql:8.0
    container_name: dev-db-ventas
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: dev_db_ventas
    ports:
      - "${DB_VENTAS_PORT}:3306"
    networks:
      - dev-network

  db-despachos:
    image: mysql:8.0
    container_name: dev-db-despachos
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: dev_db_despachos
    ports:
      - "${DB_DESPACHOS_PORT}:3306"
    networks:
      - dev-network

  back-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    ports:
      - "${BACKEND_VENTAS_PORT}:8080"
    environment:
      - DB_ENDPOINT=db-ventas
      - DB_PORT=${DB_VENTAS_PORT}
      - DB_NAME=dev_db_ventas
      - DB_USERNAME=${BD_USER}
      - DB_PASSWORD=${BD_PASS}
    depends_on:
      - db-ventas
    networks:
      - dev-network

  back-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    ports:
      - "${BACKEND_DESPACHOS_PORT}:8081"
    environment:
      - DB_ENDPOINT=db-despachos
      - DB_PORT=${DB_DESPACHOS_PORT}
      - DB_NAME=dev_db_despachos
      - DB_USERNAME=${BD_USER}
      - DB_PASSWORD=${BD_PASS}
    depends_on:
      - db-despachos
    networks:
      - dev-network

  frontend:
    build:
      context: ./front_despacho
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - back-ventas
      - back-despachos
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
