# Stage 1: Build
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

#--------------------------------
# User spring doesn't exist by default
# We create it to match the user in the build stage
#--------------------------------
RUN groupadd -r spring && useradd -r -g spring spring
USER spring:spring

# Stage 2: Run
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE ${BACKEND_VENTAS_PORT}
ENTRYPOINT ["java", "-jar", "app.jar"]
